<?php

$labels = array();

// mail

$labels['folder_contact'] = 'Kontakte-Ordner';

$labels['folder_create'] = 'Neuen Ordner anlegen';
$labels['folder_delete'] = 'Ordner löschen';
$labels['folder_rename'] = 'Ordner umbenennen';
$labels['folder_locate'] = 'Ordner suchen';

$labels['folder_purge'] = 'Ordner leeren';

$labels['folder_read_this'] = 'Ordner als gelesen markieren';
$labels['folder_read_tree'] = 'Ordnerstruktur als gelesen markieren';

$labels['show_all'] = 'Alle Ordner anzeigen';
$labels['show_active'] = 'Aktive Ordner anzeigen';
$labels['show_favorite'] = 'Favoriten anzeigen';

$labels['folder_select'] = 'Ordner zur Auswahlliste hinzufügen';
$labels['folder_unselect'] = 'Ordner von Auswahlliste entfernen';

$labels['reset_selected'] = 'Ordnerauswahlliste zurücksetzen';
$labels['reset_transient'] = 'Kurzzeitauswahl zurücksetzen';

$labels['status_title'] = 'Ordneransicht ...';

$labels['folder_expand_all'] = 'Alle Unterordner ausklappen';
$labels['folder_collapse_all'] = 'Alle Unterordner einklappen';

$labels['folder'] = 'Ordner';

$labels['reset'] = 'Zurücksetzen';
$labels['apply'] = 'Anwenden';
$labels['cancel'] = 'Abbrechen';
$labels['select'] = 'Auswählen';
$labels['search'] = 'Suchen';

$labels['source'] = 'Quelle';
$labels['target'] = 'Ziel';

$labels['create'] = 'Anlegen';
$labels['delete'] = 'Löschen';
$labels['rename'] = 'Umbenennen';
$labels['locate'] = 'Suchen';

$labels['parent'] = 'Eltern';
$labels['header'] = 'Header';
$labels['format'] = 'Format';
$labels['type'] = 'Typ';
$labels['full_name'] = 'Name';
$labels['mail_addr'] = 'E-Mail-Adresse';

$labels['message_copy'] = 'Kopieren nach ...';
$labels['message_move'] = 'Verschieben nach ...';

// settings

$labels['plugin_folder_menu'] = 'Plugin: Ordner-Kontextmenü';

$labels['activate_plugin'] = 'Plugin aktivieren';

$labels['enable_logging'] = 'Plugin Logmeldungen aktivieren';
$labels['enable_refresh'] = 'Aktualisierung der Ordnerstruktur aktivieren';
$labels['enable_folder_list_context_menu'] = 'Kontextmenü in der Postfachliste aktivieren';
$labels['enable_folder_list_control_menu'] = 'Kontrollmenü in der Postfachliste aktivieren';
$labels['enable_message_list_context_menu'] = 'Kontextmenü in der Nachrichtenliste aktivieren';

$labels['feature_choice'] = 'Aktivierte Plugin Features';

$labels['filter_active'] = 'Filter in der Kategorie "Aktiv"';
$labels['filter_favorite'] = 'Filter in der Kategorie "Favoriten"';

$labels['predefined_list'] = 'Ordner im "Vordefiniert" Filter';
$labels['contact_folder_format_list'] = 'Vorlagen für das Kontakte-Ordner Format';

$labels['transient_expire_mins'] = 'Ablaufzeit für die Ordner-Kurzzeitauswahl (Minuten)';

?>
