<?php

$labels = array();

// mail

$labels['folder_contact'] = 'Contact folder';

$labels['folder_create'] = 'Create folder';
$labels['folder_delete'] = 'Delete folder';
$labels['folder_rename'] = 'Rename folder';
$labels['folder_locate'] = 'Locate folder';

$labels['folder_tree_read'] = 'Folder tree read';

$labels['show_all'] = 'Show all';
$labels['show_active'] = 'Show active';
$labels['show_favorite'] = 'Show favorite';

$labels['folder_select'] = 'Select folder';
$labels['folder_unselect'] = 'Unselect folder';

$labels['reset_selected'] = 'Reset selected';
$labels['reset_transient'] = 'Reset transient';

$labels['status_title'] = 'Folder view...';

$labels['folder_expand_all'] = 'Expand all';
$labels['folder_collapse_all'] = 'Collapse all';

$labels['folder'] = 'Folder';

$labels['reset'] = 'Reset';
$labels['apply'] = 'Apply';
$labels['cancel'] = 'Cancel';
$labels['select'] = 'Select';
$labels['search'] = 'Search';

$labels['source'] = 'Source';
$labels['target'] = 'Target';

$labels['create'] = 'Create';
$labels['delete'] = 'Delete';
$labels['rename'] = 'Rename';
$labels['locate'] = 'Locate';

// settings

$labels['folder_menu'] = 'Folder Menu';

$labels['enable_logging'] = 'Enable plugin logging';
$labels['enable_refresh'] = 'Enable folder tree refresh';
$labels['enable_folder_list_context_menu'] = 'Enable folder list context menu';
$labels['enable_folder_list_control_menu'] = 'Enable folder list control menu';
$labels['enable_message_list_context_menu'] = 'Enable message list context menu';

$labels['filter_active'] = 'Filters in category "active"';
$labels['filter_favorite'] = 'Filters in category "favorite"';

$labels['predefined_list'] = 'Folders in "predefined" filter';

?>
